language: node_js
node_js:
  - 15

git:
  depth: false
  quiet: true

cache: yarn

after_success: yarn build-storybook --quiet && touch .out/.nojekyll

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  github_token: $GITHUB_TOKEN
  local_dir: .out
  provider: pages
  skip_cleanup: true
  on:
    branch: master
