language: node_js
node_js:
  - 14

git:
  depth: false
  quiet: true

cache: yarn

script: yarn build-storybook

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: .out
  provider: pages
  skip_cleanup: true
  on:
    branch: master
