name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Unit Test
        run: yarn test --quiet

      - name: Build StoryBook
        run: yarn build-storybook --quiet

      - name: Configure GitHub pages
        run: touch out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: .out
