name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - run: pnpm test

      - run: pnpm run build-storybook --quiet

      - name: Configure GitHub pages
        run: touch .out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          silent: true
          clean: true
          branch: gh-pages
          folder: .out
          single-commit: true
