name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm i -g pnpm
      - run: pnpm install

      - run: pnpm run test

      - name: Build StoryBook
        run: pnpm run build-storybook --quiet

      - name: Configure GitHub pages
        run: touch .out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          silent: true
          clean: true
          branch: gh-pages
          folder: .out
          single-commit: true
